CREATE TABLE IF NOT EXISTS es_annual_operations(
    "Data Year" BIGINT,
    "AEA Reporter ID" VARCHAR,
    "AEA Reporter Name" VARCHAR,
    "PCE reporting ID" NUMERIC,
    "OPERATOR_AEA Utility ID" VARCHAR,
    "EIA Utility Number" VARCHAR,
    CPCN BIGINT,
    "OPERATOR_Operator Name" VARCHAR,
    "OPERATOR_Ownership Type" VARCHAR,
    intertie_id VARCHAR,
    intertie_name VARCHAR,
    Source VARCHAR,
    "Summer Peak Demand (MW)" VARCHAR,
    "Winter Peak Demand (MW)" VARCHAR,
    "Net Generation (MWh)" NUMERIC,
    "Wholesale Power Purchases (MWh)" VARCHAR,
    "Exchange Energy Received (MWh)" VARCHAR,
    "Exchange Energy Delivered (MWh)" VARCHAR,
    "Net Power Exchanged (MWh)" NUMERIC,
    "Wheeled Power Received (MWh)" VARCHAR,
    "Wheeled Power Delivered (MWh)" VARCHAR,
    "Net Wheeled Power (MWh)" NUMERIC,
    "Transmission by Other Losses (MWh)" VARCHAR,
    "Total Sources (MWh)" NUMERIC,
    "Retail Sales (MWh)" VARCHAR,
    "Sales for Resale (MWh)" VARCHAR,
    "Furnished without Charge (MWh)" VARCHAR,
    "Consumed by Respondent without Charge (MWh)" VARCHAR,
    "Consumed by Facility (MWh)" NUMERIC,
    "Unaccountable / Energy Loss" VARCHAR,
    "Total Disposition (MWh)" NUMERIC,
    "From Retail Sales ($1000s)" VARCHAR,
    "From Delivery Customers ($1000s)" VARCHAR,
    "Unbundled Revenue ($1000s)" NUMERIC,
    "From Sales for Resale ($1000s)" VARCHAR,
    "From Credits or Adjustments ($1000s)" VARCHAR,
    "From Transmission ($1000s)" VARCHAR,
    "From Other ($1000s)" VARCHAR,
    "Total ($1000s)" NUMERIC,
    "Data Type
    O = Observed
    I = Imputed" VARCHAR,
    "Number of Records" VARCHAR,
    Notes VARCHAR);