CREATE TABLE IF NOT EXISTS es_infrastructure(
    "AEA plant ID" VARCHAR,
    "Plant Name" VARCHAR,
    "AEA operator ID" VARCHAR,
    "EIA Utility ID" NUMERIC,
    "Utility Name" VARCHAR,
    "EIA Plant Code" NUMERIC,
    "Name of Water Source" VARCHAR,
    "PCE ID" NUMERIC,
    "RCA CPCN" NUMERIC,
    "Intertie ID" VARCHAR,
    "Intertie name" VARCHAR,
    "Energy Region" VARCHAR,
    "Generator ID" VARCHAR,
    Technology VARCHAR,
    "Prime Mover" VARCHAR,
    "Data Source year" NUMERIC,
    "Data Source" VARCHAR,
    Ownership VARCHAR,
    "Nameplate Capacity (MW)" NUMERIC,
    "Storage Capacity (MWh)" NUMERIC,
    "Nameplate Power Factor" VARCHAR,
    "Summer Capacity (MW)" VARCHAR,
    "Winter Capacity (MW)" VARCHAR,
    "Minimum Load (MW)" VARCHAR,
    "Uprate or Derate Completed" VARCHAR,
    "Month Uprate or Derate Completed" VARCHAR,
    "Year Uprate or Derate Completed" VARCHAR,
    Status VARCHAR,
    "Synchronized to Transmission Grid" VARCHAR,
    "Operating Month" VARCHAR,
    "Operating Year" VARCHAR,
    "Planned or Actual Retirement Month" VARCHAR,
    "Planned or Actual Retirement Year" VARCHAR,
    "Associated with Combined Heat and Power System" VARCHAR,
    "Sector Name" VARCHAR,
    Sector NUMERIC,
    "Energy Source 1" VARCHAR,
    "Energy Source 2" VARCHAR,
    "Startup Source 1" VARCHAR,
    "Startup Source 2" VARCHAR,
    "Turbines or Hydrokinetic Buoys" VARCHAR,
    "Time from Cold Shutdown to Full Load" VARCHAR,
    "Multiple Fuels?" VARCHAR,
    "Cofire Fuels?" VARCHAR,
    "Switch Between Oil and Natural Gas?" VARCHAR,
    Notes VARCHAR,
    "Engine Make" VARCHAR,
    "Engine Model" VARCHAR,
    "Unnamed: 48" NUMERIC);